name: CI

on:
  push:
    branches:
      - master
    tags: ["*"]
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  Code-Quality:
    name: Code Quality
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cfbaptista/bolt:bolt-0.3.0

    steps:
      - name: Fix dubious ownership warning
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Configure project
        run: cmake --preset linux-x86-64-llvm-debug

      - name: Build project
        run: cmake --build --preset linux-x86-64-llvm-debug

      - name: Test project
        run: ctest --preset linux-x86-64-llvm-debug

      - name: Run formatter
        run: |
          set -x

          if ! command -v clang-format >/dev/null 2>&1; then
            echo "clang-format not found"
            exit 1
          fi

          files=$(git ls-files '*.cpp' '*.hpp' '*.tpp')

          if [ -z "$files" ]; then
            echo "No .cpp/.hpp/.tpp files to check"
            exit 0
          fi

          status=0
          for file in $files; do
            clang-format --style=file "$file" --dry-run --Werror
            if [ $? -ne 0 ]; then
              status=1
            fi
          done

          if [ $status -ne 0 ]; then
            echo "clang-format found formatting issues."
            exit 1
          fi

      - name: Run linter
        run: |
          set -x

          if ! command -v clang-tidy >/dev/null 2>&1; then
            echo "clang-tidy not found"
            exit 1
          fi

          files=$(git ls-files '*.cpp' '*.hpp')

          if [ -z "$files" ]; then
            echo "No .cpp/.hpp files to lint"
            exit 0
          fi

          output=$(clang-tidy $files -p build/linux-x86-64-llvm-debug -format-style=file -warnings-as-errors=* -quiet 2>&1)
          status=$?

          if [ $status -ne 0 ]; then
            printf '%s\n' "$output"
            echo "clang-tidy found errors."
            exit 1
          fi

      - name: Run coverage
        run: cmake --build build/linux-x86-64-llvm-debug --target Coverage

  Configure-Build-Test:
    name: Configure-Build-Test (${{ matrix.preset }})
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cfbaptista/bolt:bolt-0.3.0
    needs: Code-Quality
    strategy:
      matrix:
        preset:
          - linux-x86-64-gnu-debug
          - linux-x86-64-gnu-release
          - linux-x86-64-llvm-release
      fail-fast: true

    steps:
      - name: Checkout project
        uses: actions/checkout@v5

      - name: Configure project
        run: cmake --preset ${{ matrix.preset }}

      - name: Build project
        run: cmake --build --preset ${{ matrix.preset }}

      - name: Test project
        run: ctest --preset ${{ matrix.preset }}
